export const JamesRadfordTxData = [];

export const MichelleWilliamsTxData = [
  {
    txName: "",
    whatUsed: "Credit",
    credit: "+$850,000.00",
    date: "Oct 16, 2023",
    color: "green",
  },
];

export const JamesSterlingBargerTxData = [
  {
    txName: "Andrew Goldberg",
    whatUsed: "Credit",
    debit: "+$100,000,000.00",
    date: "Oct 06, 2023",
    color: "green",
  },
  {
    txName: "President of pch",
    whatUsed: "Credit",
    debit: "+$100,000,000.00",
    date: "Oct 06, 2023",
    color: "green",
  },
  {
    txName: "Etfashion",
    whatUsed: "Credit",
    debit: "+$200,000.00",
    date: "Jun 19, 2023",
    color: "green",
  },
  {
    txName: "Headquarters Construction",
    whatUsed: "Debit",
    debit: "-$75,000.00",
    date: "Jun 04, 2023",
    color: "red",
  },
  {
    txName: "Gebbers Farms",
    whatUsed: "Credit",
    debit: "+$500,000.00",
    date: "May 05, 2023",
    color: "green",
  },
  {
    txName: "Busch Agricultural Resources",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "May 01, 2023",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$400,000.00",
    date: "Apr 25, 2023",
    color: "red",
  },
  {
    txName: "Farm.One",
    whatUsed: "Credit",
    debit: "+$85,000.00",
    date: "Mar 03, 2023",
    color: "green",
  },
  {
    txName: "IJH FARM",
    whatUsed: "Credit",
    debit: "+$150,000.00",
    date: "Feb 10, 2023",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$500,000.00",
    date: "Jan 15, 2023",
    color: "red",
  },
  {
    txName: "Summit Agricultural Group",
    whatUsed: "Credit",
    debit: "+$135,000.00",
    date: "Jan 1, 2023",
    color: "green",
  },
  {
    txName: "Follow Suit Swimwear",
    whatUsed: "credit",
    debit: "+$195,000.00",
    date: "Dec 29, 2022",
    color: "green",
  },
  {
    txName: "Brunt Workwear",
    whatUsed: "credit",
    debit: "+$92,280.00",
    date: "Dec 21, 2022",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$237,350.00",
    date: "Dec 18, 2022",
    color: "red",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$40,000.00",
    date: "Dec 16, 2022",
    color: "red",
  },
  {
    txName: "Prestage Farms of Iowa",
    whatUsed: "Credit",
    debit: "+$100,000.00",
    date: "Dec 08, 2022",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$500,000.00",
    date: "Dec 04, 2022",
    color: "red",
  },
];

export const JessicalKevinTxData = [
  {
    txName: "Andrew Goldberg",
    whatUsed: "Credit",
    debit: "+$2,000,000.00",
    date: "Sept 25, 2023",
    color: "green",
  },
  {
    txName: "President of pch",
    whatUsed: "Credit",
    debit: "+$500,000.00",
    date: "Sept 20, 2023",
    color: "green",
  },
  {
    txName: "Etfashion",
    whatUsed: "Credit",
    debit: "+$200,000.00",
    date: "Sept 10, 2023",
    color: "green",
  },
  {
    txName: "Headquarters Construction",
    whatUsed: "Debit",
    debit: "-$75,000.00",
    date: "Sept 04, 2023",
    color: "red",
  },
  {
    txName: "Gebbers Farms",
    whatUsed: "Credit",
    debit: "+$500,000.00",
    date: "Sept 01, 2023",
    color: "green",
  },
  {
    txName: "Busch Agricultural Resources",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "Aug 18, 2023",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$400,000.00",
    date: "Aug 17, 2023",
    color: "red",
  },
  {
    txName: "Farm.One",
    whatUsed: "Credit",
    debit: "+$85,000.00",
    date: "Aug 09, 2023",
    color: "green",
  },
  {
    txName: "IJH FARM",
    whatUsed: "Credit",
    debit: "+$150,000.00",
    date: "Aug 7, 2023",
    color: "green",
  },
  {
    txName: "Brunt Workwear",
    whatUsed: "credit",
    debit: "+$92,280.00",
    date: "Aug 3, 2023",
    color: "green",
  },
];
