const users = [
  {
    id: 1,
    name: "James Radford",
    cardName: "James Radford",
    username: "Jamesradford1",
    password: "James01",
    amount: "1,010,000.00",
  },
  {
    id: 2,
    name: "Michelle Williams",
    jointAccountName: "Joseph Zarcone",
    cardName: "Michelle Williams",
    username: "Joseph&Michelle2023",
    password: "MichelleluvJoseph",
    amount: "850,000.00",
  },
  {
    id: 3,
    name: "James Sterling Barger",
    cardName: "James sterling b.",
    username: "Jamesbarger236",
    password: "James barger",
    amount: "200,000,000.00",
  },
  {
    id: 4,
    name: "Jessica Kelvin",
    cardName: "Jessica Kelvin",
    username: "Jessicakelvin91",
    password: "Lordisgood12345",
    amount: "14,200,000.00",
    checkingAccountAmount: "10,000,000.00",
    savingAccountAmount: "4,200,000.00",
  },
  {
    id: 5,
    name: "VARONE EMILY ANNE",
    cardName: "VARONE EMILY ANNE",
    username: "emilyvaronesienna",
    password: "GODISGREAT2011",
    amount: "25,000,000.00",
  },
  {
    id: 6,
    name: "Allison Dean",
    cardName: "Allison Dean",
    username: "AllisonDean",
    password: "DeanAllison",
    amount: "200,000.00",
  },
  {
    id: 7,
    name: "Sandra Annette Bullock",
    cardName: "Sandra Annette Bullock",
    username: "sandraannette2288",
    password: "Annette2288",
    amount: "100,000,000.00",
  },
];
export default users;
